version: "3"

services:
    ttrss:
        container_name: ttrss
        image: local/ttrss
        build:
            context: .
        restart: always
        volumes:
            - /mnt/storage/docker/volumes/ttrss/config.php:/var/www/tt-rss/config.php
        ports:
            - "8000:80"
